name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    types:
    - opened
    - synchronize

# Add these permissions at the workflow level
permissions:
  contents: write  # This is required for creating releases

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Check style against standards
        run: uv run make lint

  coverage:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run unit tests with coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage html --show-contexts --title "Extendable Agents Coverage for ${{ github.sha }}"
          uv run coverage xml
          uv run diff-cover coverage.xml --html-report index.html

      - name: Store coverage html
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true

      - name: Store diff coverage html
        uses: actions/upload-artifact@v4
        with:
          name: diff-coverage-html
          path: index.html

      # - run: uv run coverage report --fail-under 95
      # - run: uv run diff-cover coverage.xml --fail-under 100

  build-and-release:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: yezz123/setup-uv@v4

      - name: Build project
        run: uv build

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
